version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - errorlint
  settings:
    misspell:
      locale: UK
    revive:
      rules:
        - name: exported
        - name: indent-error-flow
        - name: error-strings
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
