package textguard

import (
	"fmt"
	"strings"

	"github.com/tamnd/kvant-solver/manifest"
)

// Price is what a vision page is taken to cost. Every field is an assumption
// until a real decade has run, which is why the report prints them next to the
// numbers they produced: a cost estimate whose inputs are hidden is a number
// nobody can disagree with, and disagreeing with it is the point.
type Price struct {
	// InputTokens is a page image plus the prompt. OutputTokens is the
	// transcription, which for a dense two column page of mathematics is longer
	// than people expect.
	InputTokens  int
	OutputTokens int

	// The two rates, in dollars per million tokens.
	InputRate  float64
	OutputRate float64

	// SecondsPerPage is how long one page takes on one lane, including the
	// retries a page of Cyrillic mathematics needs. Lanes is how many run at
	// once.
	SecondsPerPage float64
	Lanes          int
}

// DefaultPrice is the estimate the milestones were written against: a mid
// priced vision model, eight lanes, and two and a half minutes a page on a
// lane once retries are counted. That puts the sixteen thousand pages of the
// Soviet decades at about six hundred and sixty lane hours, which is four days
// across eight lanes and a month across one.
var DefaultPrice = Price{
	InputTokens:    1800,
	OutputTokens:   1400,
	InputRate:      0.30,
	OutputRate:     1.20,
	SecondsPerPage: 148,
	Lanes:          8,
}

// PageCost is what one vision page costs in dollars.
func (p Price) PageCost() float64 {
	return float64(p.InputTokens)/1e6*p.InputRate + float64(p.OutputTokens)/1e6*p.OutputRate
}

// Cost is what a number of vision pages costs.
func (p Price) Cost(pages int) float64 { return float64(pages) * p.PageCost() }

// LaneHours is how long a number of vision pages takes on one lane.
func (p Price) LaneHours(pages int) float64 { return float64(pages) * p.SecondsPerPage / 3600 }

// Days is how long a number of vision pages takes across the lanes there are.
func (p Price) Days(pages int) float64 {
	lanes := max(p.Lanes, 1)
	return p.LaneHours(pages) / float64(lanes) / 24
}

// Report writes reports/paths.md: what each year is going to cost to read, and
// what was measured to arrive at that.
func Report(paths *manifest.Paths, price Price) string {
	var b strings.Builder
	b.WriteString("# How every page gets read\n\n")
	b.WriteString("Three ways to get the text of a page, in order of what they cost. ")
	b.WriteString("`native` is the text layer of the publisher's own PDF and is free. ")
	b.WriteString("`publisher` is the transcription kvant.digital already carries for an article and is also free, though it is somebody else's OCR and gets checked against a vision pass on a sample. ")
	b.WriteString("`vision` is a model reading a scan, and it is the only one that costs anything.\n\n")
	b.WriteString("This file is generated by `kvant textguard`. The page by page decision lives in the page manifests next to the scans; what is here is the count and the measurement behind it.\n\n")

	writeYears(&b, paths, price)
	writeDecades(&b, paths, price)
	writeBorn(&b, paths)
	writeAssumptions(&b, price)
	return b.String()
}

func writeYears(b *strings.Builder, paths *manifest.Paths, price Price) {
	b.WriteString("## By year\n\n")
	b.WriteString("| Year | Issues | Pages | Native | Publisher | Vision | Cost | Lane hours |\n")
	b.WriteString("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
	for _, year := range paths.YearList() {
		issues := paths.Year(year)
		c := paths.Count(func(iss manifest.IssuePaths) bool { return iss.Year == year })
		fmt.Fprintf(b, "| %d | %d | %d | %d | %d | %d | $%.0f | %.0f |\n",
			year, len(issues), c.Total(), c.Native, c.Publisher, c.Vision,
			price.Cost(c.Vision), price.LaneHours(c.Vision))
	}
	t := paths.Totals
	fmt.Fprintf(b, "| **all** | **%d** | **%d** | **%d** | **%d** | **%d** | **$%.0f** | **%.0f** |\n\n",
		len(paths.Issues), t.Total(), t.Native, t.Publisher, t.Vision,
		price.Cost(t.Vision), price.LaneHours(t.Vision))

	if t.Undecided > 0 {
		fmt.Fprintf(b, "%d sheets have no decision yet, which means they have not been downloaded. Run `kvant fetch pages` and this again.\n\n", t.Undecided)
	}
}

func writeDecades(b *strings.Builder, paths *manifest.Paths, price Price) {
	years := paths.YearList()
	if len(years) == 0 {
		return
	}
	b.WriteString("## By decade\n\n")
	fmt.Fprintf(b, "Wall clock is across %d lanes.\n\n", max(price.Lanes, 1))
	b.WriteString("| Decade | Pages | Vision | Cost | Lane hours | Days |\n")
	b.WriteString("| --- | ---: | ---: | ---: | ---: | ---: |\n")

	first, last := years[0]/10*10, years[len(years)-1]/10*10
	for decade := first; decade <= last; decade += 10 {
		c := paths.Count(func(iss manifest.IssuePaths) bool {
			return iss.Year >= decade && iss.Year < decade+10
		})
		if c.Total() == 0 {
			continue
		}
		fmt.Fprintf(b, "| %ds | %d | %d | $%.0f | %.0f | %.1f |\n",
			decade, c.Total(), c.Vision, price.Cost(c.Vision), price.LaneHours(c.Vision), price.Days(c.Vision))
	}
	b.WriteString("\n")
}

// writeBorn is the part that keeps the native path honest. The plan says the
// PDFs from 2007 on are born digital; this says which years that was actually
// measured on and where it did not hold.
func writeBorn(b *strings.Builder, paths *manifest.Paths) {
	type row struct {
		year           int
		born, measured int
		issues         int
		scan           string
	}
	var rows []row
	for _, year := range paths.YearList() {
		born, measured := paths.Born(year)
		if measured == 0 {
			continue
		}
		r := row{year: year, born: born, measured: measured, issues: len(paths.Year(year))}
		for _, iss := range paths.Year(year) {
			if iss.PDF != nil && !iss.PDF.Born {
				r.scan = iss.Key + ": " + iss.PDF.Why
				break
			}
		}
		rows = append(rows, r)
	}
	if len(rows) == 0 {
		return
	}

	b.WriteString("## Which PDFs are born digital\n\n")
	b.WriteString("Measured, not assumed: embedded fonts, a body page that carries thousands of characters rather than a page number, and letters that are actually Russian rather than mojibake.\n\n")
	b.WriteString("| Year | Issues | With a PDF | Born digital |\n")
	b.WriteString("| --- | ---: | ---: | ---: |\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %d | %d | %d | %d |\n", r.year, r.issues, r.measured, r.born)
	}
	b.WriteString("\n")

	var bad []string
	for _, r := range rows {
		if r.scan != "" {
			bad = append(bad, r.scan)
		}
	}
	if len(bad) > 0 {
		b.WriteString("Files the mirror has that are scans in a PDF wrapper, one example per year:\n\n")
		for _, line := range bad {
			b.WriteString("- " + line + "\n")
		}
		b.WriteString("\n")
	}
}

func writeAssumptions(b *strings.Builder, price Price) {
	b.WriteString("## What the estimates assume\n\n")
	b.WriteString("These are assumptions and not measurements. They are here so that the numbers above can be argued with, and they get replaced with what M3 actually measures on one issue.\n\n")
	fmt.Fprintf(b, "- One model call per page: %d input tokens for the image and the prompt, %d output tokens for the transcription.\n",
		price.InputTokens, price.OutputTokens)
	fmt.Fprintf(b, "- $%.2f per million input tokens and $%.2f per million output, which comes to $%.4f a page.\n",
		price.InputRate, price.OutputRate, price.PageCost())
	fmt.Fprintf(b, "- %.0f seconds a page on one lane, retries included, across %d lanes.\n",
		price.SecondsPerPage, max(price.Lanes, 1))
	b.WriteString("- Nothing here counts the second pass on pages that come back illegible, or the translation runs, which are priced separately.\n")
}
