package manifest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func store(t *testing.T) *Store {
	t.Helper()
	root := t.TempDir()
	s, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	return s
}

func TestWriteThenRead(t *testing.T) {
	s := store(t)
	m := &Issues{}
	for _, n := range []string{"1", "5-6", "2"} {
		iss, err := NewIssue(1976, n)
		if err != nil {
			t.Fatal(err)
		}
		m.Add(iss)
	}
	m.Sort()
	if err := s.Write(IssuesFile, m, "three issues of 1976"); err != nil {
		t.Fatal(err)
	}

	var got Issues
	if err := s.Read(IssuesFile, &got); err != nil {
		t.Fatal(err)
	}
	if got.Count != 3 || got.Years != 1 {
		t.Errorf("counts came back as %d issues in %d years", got.Count, got.Years)
	}
	want := []string{"1", "2", "5-6"}
	for i, w := range want {
		if got.Issues[i].Number != w {
			t.Errorf("issue %d is number %q, want %q", i, got.Issues[i].Number, w)
		}
	}
	// A double issue has to sort where the shelf puts it, not where a string
	// comparison puts it.
	if got.Issues[2].Dir != "1976/05-06" {
		t.Errorf("the double issue is filed at %q", got.Issues[2].Dir)
	}
}

func TestWrittenFileSaysItIsGenerated(t *testing.T) {
	s := store(t)
	m := &Issues{}
	iss, _ := NewIssue(1975, "1")
	m.Add(iss)
	m.Sort()
	if err := s.Write(IssuesFile, m, "the note"); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(s.Path(IssuesFile))
	if err != nil {
		t.Fatal(err)
	}
	head := string(b)
	if !strings.HasPrefix(head, "# Generated by kvant.") {
		t.Errorf("the file does not open with a generated notice: %.60q", head)
	}
	if !strings.Contains(head, "# the note") {
		t.Error("the note did not make it into the header")
	}
}

func TestReadingAMissingManifestSaysSo(t *testing.T) {
	s := store(t)
	var m Issues
	err := s.Read(IssuesFile, &m)
	if err == nil {
		t.Fatal("reading a manifest that was never written should fail")
	}
	// The first run of every sync command hits this, and it is not a fault, so
	// it has to be tellable from a real read error.
	if !strings.Contains(err.Error(), "no such manifest") {
		t.Errorf("error is %v", err)
	}
}

func TestUnknownFieldsAreAnError(t *testing.T) {
	s := store(t)
	body := "years: 1\ncount: 1\nissues:\n  - key: kvant_1975_1\n    year: 1975\n    number: \"1\"\n    dir: 1975/01\n    sources: {}\n    colour: blue\n"
	if err := os.WriteFile(s.Path(IssuesFile), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	var m Issues
	if err := s.Read(IssuesFile, &m); err == nil {
		t.Fatal("a key nothing reads should be an error, not silent data loss")
	}
}

func TestWriteIsAtomic(t *testing.T) {
	s := store(t)
	m := &Issues{}
	iss, _ := NewIssue(1975, "1")
	m.Add(iss)
	m.Sort()
	if err := s.Write(IssuesFile, m); err != nil {
		t.Fatal(err)
	}
	if err := s.Write(IssuesFile, m); err != nil {
		t.Fatal(err)
	}
	// A temp file left behind would be committed by whoever runs the sync next.
	entries, err := os.ReadDir(s.Dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.Name() != IssuesFile {
			t.Errorf("%s was left in the manifests directory", e.Name())
		}
	}
	if s.Path(IssuesFile) != filepath.Join(s.Dir, IssuesFile) {
		t.Error("Path does not agree with Dir")
	}
	// The manifests are committed to a public repository, so they cannot come
	// out with the private permissions a temporary file is created with.
	info, err := os.Stat(s.Path(IssuesFile))
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o644 {
		t.Errorf("the manifest is mode %v", info.Mode().Perm())
	}
}

func TestMergeFillsInRatherThanReplaces(t *testing.T) {
	m := &Issues{}
	iss, _ := NewIssue(1975, "1")
	iss.Sources.Digital = &Digital{URL: "https://www.kvant.digital/issues/1975/1/", Rows: 24}
	m.Add(iss)

	// The second source only knows about itself, and must not wipe the first.
	later, _ := NewIssue(1975, "1")
	later.Sources.MathNet = &MathNet{URL: "https://www.mathnet.ru/x", Number: "1"}
	m.Add(later)

	got, ok := m.Get("kvant_1975_1")
	if !ok {
		t.Fatal("the issue went missing")
	}
	if got.Sources.Digital == nil || got.Sources.Digital.Rows != 24 {
		t.Error("the second source replaced the first instead of filling in")
	}
	if got.Sources.MathNet == nil {
		t.Error("the second source was not recorded")
	}
	if len(m.Issues) != 1 {
		t.Errorf("the same issue was added twice, %d rows", len(m.Issues))
	}
}

func TestIssueNumberOrdering(t *testing.T) {
	for _, tc := range []struct {
		number string
		first  int
		month  string
	}{
		{"1", 1, "01"},
		{"11-12", 11, "11"},
		{"5-6", 5, "05"},
	} {
		if got := FirstNumber(tc.number); got != tc.first {
			t.Errorf("FirstNumber(%q) = %d", tc.number, got)
		}
		if got := Month(tc.number); got != tc.month {
			t.Errorf("Month(%q) = %q", tc.number, got)
		}
	}
}

func TestTOCRoundTrip(t *testing.T) {
	s := store(t)
	toc := &TOC{}
	toc.Set("kvant_1975_2", []Row{{Title: "second issue", Page: 3, Source: "kvant.digital"}})
	toc.Set("kvant_1975_1", []Row{
		{Title: "later", Page: 10, Source: "kvant.digital"},
		{Title: "earlier", Page: 2, Source: "kvant.digital"},
	})
	toc.Sort()
	if toc.Issues[0].Key != "kvant_1975_1" {
		t.Errorf("issues came out in the order %q", toc.Issues[0].Key)
	}
	if toc.Issues[0].Rows[0].Title != "earlier" {
		t.Error("rows are not in printed page order")
	}
	if toc.Rows() != 3 {
		t.Errorf("counted %d rows", toc.Rows())
	}
	if err := s.Write(TOCFile, toc); err != nil {
		t.Fatal(err)
	}
	var got TOC
	if err := s.Read(TOCFile, &got); err != nil {
		t.Fatal(err)
	}
	if got.Rows() != 3 {
		t.Errorf("read back %d rows", got.Rows())
	}
}

func TestPersonaliaKeepsVariants(t *testing.T) {
	p := &Personalia{}
	p.Add(Person{Slug: "kolmogorov_an", Name: "Колмогоров А. Н.", Items: 3})
	p.Add(Person{Slug: "kolmogorov_an", Name: "А. Н. Колмогоров", Items: 1})
	p.Sort()
	if len(p.People) != 1 {
		t.Fatalf("%d people, the two spellings should have merged", len(p.People))
	}
	if p.People[0].Items != 4 {
		t.Errorf("items came to %d", p.People[0].Items)
	}
	// The second spelling is kept rather than dropped, because a search for it
	// still has to find the person.
	if len(p.People[0].Variants) != 1 {
		t.Errorf("variants are %v", p.People[0].Variants)
	}
}

func TestRubricsFoldSpellingVariants(t *testing.T) {
	r := &Rubrics{}
	r.Observe("Задачник «Кванта»", 1975)
	r.Observe("Задачник «Кванта»", 1976)
	r.Observe("задачник Кванта", 1988)
	r.Observe("Квант для младших школьников", 1975)
	r.Sort()

	if len(r.Rubrics) != 2 {
		for _, x := range r.Rubrics {
			t.Logf("%s %d", x.Slug, x.Count)
		}
		t.Fatalf("%d rubrics, the guillemets should not make a new one", len(r.Rubrics))
	}
	first := r.Rubrics[0]
	if first.Count != 3 {
		t.Errorf("the commonest rubric has count %d", first.Count)
	}
	if first.First != 1975 || first.Last != 1988 {
		t.Errorf("years run %d to %d", first.First, first.Last)
	}
	// The canonical name is the spelling seen most often, and the other is
	// kept as evidence.
	if first.Name != "Задачник «Кванта»" {
		t.Errorf("canonical name is %q", first.Name)
	}
	if len(first.Variants) != 2 {
		t.Errorf("variants are %v", first.Variants)
	}
}

func TestRubricSlugFoldsYo(t *testing.T) {
	// The magazine writes ё when it feels like it. Two banners that differ only
	// there are the same section.
	if RubricSlug("Всё о шаре") != RubricSlug("Все о шаре") {
		t.Error("ё and е came out as different rubrics")
	}
}

func TestErrataKeepAHumanResolution(t *testing.T) {
	e := &Errata{}
	e.Add(Erratum{
		Issue:   "kvant_1975_1",
		Kind:    "page",
		Subject: "Равенства из спичек",
		Claims:  map[string]string{"kvant.digital": "12", "kvant.mccme.ru": "13"},
	})
	if len(e.Open()) != 1 {
		t.Fatal("a fresh disagreement should be open")
	}
	e.Entries[0].Resolution = "the title appears on page 12 in the scan"
	e.Entries[0].Taken = "kvant.digital"

	// Running the sync again finds the same disagreement. Losing the answer a
	// person wrote is the one thing this file must never do.
	e.Add(Erratum{
		Issue:   "kvant_1975_1",
		Kind:    "page",
		Subject: "Равенства из спичек",
		Claims:  map[string]string{"kvant.digital": "12", "kvant.mccme.ru": "13"},
	})
	e.Sort()
	if e.Count != 1 {
		t.Errorf("%d entries after a resync", e.Count)
	}
	if len(e.Open()) != 0 {
		t.Error("the resync reopened a resolved disagreement")
	}
	if e.Entries[0].Taken != "kvant.digital" {
		t.Error("the resolution was lost")
	}
}

func TestCarryDropsWhatIsNoLongerTrue(t *testing.T) {
	old := &Errata{Entries: []Erratum{
		{Issue: "kvant_1975_1", Kind: "toc_row", Subject: "Равенства из спичек"},
		{Issue: "kvant_1975_2", Kind: "toc_row", Subject: "В номере", Resolution: "the mirror lost the row"},
		{Issue: "kvant_1993_2", Kind: "number", Subject: "2"},
	}}
	// This run looked at 1975 again and found one of the two disagreements.
	fresh := &Errata{}
	fresh.Add(Erratum{Issue: "kvant_1975_2", Kind: "toc_row", Subject: "В номере"})
	fresh.Add(Erratum{Issue: "kvant_1993_2", Kind: "number", Subject: "2"})
	fresh.Carry(old, func(x Erratum) bool { return KeyYear(x.Issue) == 1975 })
	fresh.Sort()

	if fresh.Count != 2 {
		t.Fatalf("%d entries, want 2", fresh.Count)
	}
	// A parser fix means the disagreement is gone, and the entry has to go with
	// it. An errata file that only ever grows stops being a list of findings.
	for _, x := range fresh.Entries {
		if x.Subject == "Равенства из спичек" {
			t.Error("a disagreement that is no longer there survived the resync")
		}
	}
	if fresh.Entries[0].Resolution == "" {
		t.Error("the resolution was lost, which is the one thing Carry must not do")
	}
}

func TestCarryLeavesTheYearsARunDidNotVisitAlone(t *testing.T) {
	old := &Errata{Entries: []Erratum{
		{Issue: "kvant_1980_4", Kind: "toc_row", Subject: "Гипербола"},
	}}
	fresh := &Errata{}
	fresh.Carry(old, func(x Erratum) bool { return KeyYear(x.Issue) == 1975 })
	// A sync over 1975 says nothing about 1980, and dropping the entry would
	// read as a claim that 1980 is clean.
	if len(fresh.Entries) != 1 {
		t.Errorf("%d entries, the 1980 finding should have been carried across", len(fresh.Entries))
	}
}
