// Package manifest reads and writes the YAML files under manifests/ in a
// corpus checkout. A manifest is what one source said, written down, so that
// the next stage can run without the network and so that a change in what a
// source says shows up as a diff in a pull request rather than as different
// behaviour on a Tuesday.
package manifest

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// The files this package knows about.
const (
	IssuesFile     = "issues.yaml"
	TOCFile        = "toc.yaml"
	PersonaliaFile = "personalia.yaml"
	RubricsFile    = "rubrics.yaml"
	ErrataFile     = "errata.yaml"
)

// ErrMissing is returned for a manifest that has not been written yet. It is
// worth telling apart from a read error, because the first run of any sync
// command hits it and that is not a fault.
var ErrMissing = errors.New("no such manifest")

// Store is the manifests directory of a corpus checkout.
type Store struct {
	Dir string
}

// Open points at the manifests directory of a corpus, creating it if the
// checkout does not have one yet.
func Open(corpusRoot string) (*Store, error) {
	if corpusRoot == "" {
		return nil, fmt.Errorf("no corpus path given")
	}
	abs, err := filepath.Abs(corpusRoot)
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(abs, "manifests")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	return &Store{Dir: dir}, nil
}

// Path is where a named manifest lives.
func (s *Store) Path(name string) string { return filepath.Join(s.Dir, name) }

// Exists reports whether a manifest has been written.
func (s *Store) Exists(name string) bool {
	_, err := os.Stat(s.Path(name))
	return err == nil
}

// Read decodes a manifest. Unknown fields are an error: a manifest with a key
// nothing reads is either a typo or a schema change, and both are worth
// stopping for.
func (s *Store) Read(name string, v any) error {
	f, err := os.Open(s.Path(name))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("%s: %w", name, ErrMissing)
		}
		return err
	}
	defer func() { _ = f.Close() }()

	dec := yaml.NewDecoder(f)
	dec.KnownFields(true)
	if err := dec.Decode(v); err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	return nil
}

// Write encodes a manifest, with a header saying what generated it. It writes
// to a temporary file in the same directory and renames, so a run that is
// killed part way through leaves the old manifest intact rather than half of
// the new one.
func (s *Store) Write(name string, v any, note ...string) error {
	var buf bytes.Buffer
	buf.WriteString("# Generated by kvant. Do not edit by hand: the next sync overwrites it.\n")
	for _, line := range note {
		for l := range strings.SplitSeq(line, "\n") {
			buf.WriteString("# " + l + "\n")
		}
	}

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(s.Dir, "."+name+".*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.Write(buf.Bytes()); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	// CreateTemp makes the file private to the user. A manifest is committed to
	// a public repository and read by everything downstream, so it gets the
	// permissions a checked out file would have.
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), s.Path(name))
}
