package kvantmccme

import (
	"bytes"
	"context"
	"errors"
	"fmt"

	"github.com/tamnd/kvant-solver/source"
)

// Client fetches and parses the MCCME mirror.
type Client struct {
	Fetcher *source.Client
}

// New returns a client with the default manners.
func New() *Client { return &Client{Fetcher: source.NewClient()} }

// Contents returns one issue's contents in the ordering the mirror generates
// by author.
func (c *Client) Contents(ctx context.Context, year int, month string) (*Contents, error) {
	return c.contents(ctx, IssueURL(year, month), year, month)
}

// ContentsByTitle returns the same issue in the ordering generated by title.
// The two are generated separately from the same data, so a row present in one
// and missing from the other is a fault in the mirror worth recording.
func (c *Client) ContentsByTitle(ctx context.Context, year int, month string) (*Contents, error) {
	return c.contents(ctx, IssueByTitleURL(year, month), year, month)
}

func (c *Client) contents(ctx context.Context, u string, year int, month string) (*Contents, error) {
	resp, err := c.Fetcher.Get(ctx, u)
	if err != nil {
		return nil, err
	}
	out, err := ParseContents(bytes.NewReader(resp.Body), year, month)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", u, err)
	}
	return out, nil
}

// AuthorIndex returns the authors under one initial letter.
func (c *Client) AuthorIndex(ctx context.Context, letter rune) ([]Author, error) {
	u, ok := LetterURL(letter)
	if !ok {
		return nil, fmt.Errorf("%q has no page in the author index", letter)
	}
	resp, err := c.Fetcher.Get(ctx, u)
	if err != nil {
		return nil, err
	}
	authors, err := ParseAuthorIndex(bytes.NewReader(resp.Body))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", u, err)
	}
	return authors, nil
}

// Authors returns the whole author index, one request per letter.
func (c *Client) Authors(ctx context.Context) ([]Author, error) {
	var out []Author
	for _, letter := range Letters {
		authors, err := c.AuthorIndex(ctx, letter)
		if err != nil {
			if errors.Is(err, source.ErrNotFound) {
				continue
			}
			return out, err
		}
		out = append(out, authors...)
	}
	return out, nil
}

// Archive reads the mirror's front page, which lists every issue, PDF and DjVu
// it holds. One request answers what would otherwise be a hundred HEADs, and it
// answers with URLs the mirror itself published rather than ones we made up.
func (c *Client) Archive(ctx context.Context) (*Archive, error) {
	resp, err := c.Fetcher.Get(ctx, ArchiveURL())
	if err != nil {
		return nil, err
	}
	out, err := ParseArchive(bytes.NewReader(resp.Body))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", ArchiveURL(), err)
	}
	return out, nil
}
